In [1]:
import numpy

dt = 10**-11
nt = 100

u = numpy.array([10**5,
                2*10**5,
                1.5*10**5])

E = numpy.array([1000, 0, 0])

B = numpy.array([0,0,0.1])

x = numpy.array([u,E,B])

m = 9.109*10**-31

e = 1.602*10**-19

def plasmastep(u,E,B, nt, dt,e,m):
    
    velocity = numpy.zeros((nt, 3))
    trajectory = numpy.zeros((nt, 3))
    
    velocity[0] = u
    
    for n in range(1, nt):
        velocity[n] = velocity[n-1] + (E - numpy.cross(velocity[n-1],B))*((dt*e)/m)
        trajectory[n] = velocity[n]*dt + trajectory[n-1]
        
    return trajectory

solution = plasmastep(u,E,B, nt, dt,e,m)

print(solution)



[[  0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  6.65846965e-07   2.17587002e-06   1.50000000e-06]
 [  9.66610630e-07   4.46884256e-06   3.00000000e-06]
 [  8.81696175e-07   6.81471040e-06   4.50000000e-06]
 [  4.01800899e-07   9.14564435e-06   6.00000000e-06]
 [ -4.70448771e-07   1.13921791e-05   7.50000000e-06]
 [ -1.72020955e-06   1.34853113e-05   9.00000000e-06]
 [ -3.32050252e-06   1.53586480e-05   1.05000000e-05]
 [ -5.23267225e-06   1.69505412e-05   1.20000000e-05]
 [ -7.40722127e-06   1.82061410e-05   1.35000000e-05]
 [ -9.78500565e-06   1.90793029e-05   1.50000000e-05]
 [ -1.22987660e-05   1.95342838e-05   1.65000000e-05]
 [ -1.48749569e-05   1.95471696e-05   1.80000000e-05]
 [ -1.74358270e-05   1.91069807e-05   1.95000000e-05]
 [ -1.99016941e-05   1.82164115e-05   2.10000000e-05]
 [ -2.21933497e-05   1.68921702e-05   2.25000000e-05]
 [ -2.42345240e-05   1.51648954e-05   2.40000000e-05]
 [ -2.59543354e-05   1.30786392e-05   2.55000000e-05]
 [ -2.72896500e-05   1.06899

In [2]:
import matplotlib
from mpl_toolkits.mplot3d import Axes3D
import matplotlib.pyplot as plt

In [ ]:
#Axes3D.plot(xs = solution[:,0], ys = solution[:,1], zs = solution[:,2])
#x = solution[:,0]
#y = solution[:,1]
#z = solution[:,2]

x = [1,2,3,4]
y = [3,6,8,9]
z = [1,2,3,4]

fig = plt.figure(figsize=(7,5))
ax = Axes3D(fig)

# plot data
line1 = ax.plot(x,y,z,'ok')

#modify axes
ax.minorticks_on()
ax.tick_params(axis='both',which='minor',length=5,width=2,labelsize=18)
ax.tick_params(axis='both',which='major',length=8,width=2,labelsize=18)

#display 
plt.show()