Sod's Assignment

Shock tube problem

A shock tube is an idealized device that generates a one-dimension shock wave in a compressible gas.

**See notebook for detailed illustrations of the problem and description.

The Euler Equations

For velocity u in the x direction:

$$
\frac{\partial \rho}{\partial x} + \frac{\partial}{\partial x}(\rho u) = 0$$

$$ \frac{\partial}{\partial t}(\rho u) + \frac{\partial}{\partial x} (\rho u^2 + p) = 0$$

Plus energy equation in this form:

$$\frac{\partial}{\partial t} (\rho e_T) + \frac{\partial}{\partial x} (\rho u e_T + pu)=0$$

Written in vector form:

$$\frac{\partial}{\partial t} \vec{u} + \frac{\partial}{\partial x} \vec{f} = 0$$



The conservative form

The conserved variables $\vec{u}$ for Euler's equation are

$$\vec{u} = \left[ \begin{array}{c}
\rho \\
\rho u \\
\rho e_T \\
\end{array} \right]$$

Where $\rho$ is the density of the fluid, $u$ is the velocity, and $e_T = e + \frac{u^2}{2}$ is specific total energy; $\vec{f}$ is the flux vector.

$$\vec{f} = \left[ \begin{array}{c}
\rho u \\
\rho u^2 + p \\
(\rho e_T + p)u \\
\end{array} \right]$$

where $p$ is the pressure of the fluid

$$\frac{\partial}{\partial t} \left[ \begin{array}{c}
\rho \\
\rho u \\
\rho e_T \\
\end{array} \right] + \frac{\partial}{\partial x} \left[ \begin{array}{c}
\rho u \\
\rho u^2 + p \\
(\rho e_T + p)u \\
\end{array} \right] = 0$$



Calculating the pressure

for ideal gas the equation of state is:

$$e = e(\rho, p) = \frac{p}{(\gamma - 1) \rho}$$

where $\gamma = 1.4$

$$\therefore p = (\gamma - 1) \rho e$$

Recall from above that:

$$e_T = e + \frac{1}{2}u^2$$

$$\therefore e = e_T - \frac{1}{2}u^2$$

Putting it all together:

$$p = (\gamma -1)\left( pe_T - \frac{\rho u^2}{2} \right)$$



Flux in terms of u

$$\vec{f} = f(\vec{u}$$

We need to represent f in terms of u, we will introduce this shorthand:

$$\vec{u} = \left[ \begin{array}{c}
u_1 \\
u_2 \\
u_3 \\
\end{array} \right] =  \left[ \begin{array}{c}
\rho \\
\rho u \\
\rho e_T \\
\end{array} \right]$$

$$\vec{f} = \left[ \begin{array}{c}
f_1 \\
f_2 \\
f_3 \\
\end{array} \right] = \left[ \begin{array}{c}
\rho u \\
\rho u^2 + p \\
(\rho e_T + p)u \\
\end{array} \right]$$


With smoe algebraic trickery we can represent pressure vector using quantities from u:

$$p = (\gamma -1) \left(u_3 - \frac{1}{2}\frac{u_2^2}{u_1} \right)$$


Now that f can be represented in terms of u, the rest of f isn't too hard to resolve!

$$\vec{f} = \left[ \begin{array}{c}
f_1 \\
f_2 \\
f_3 \\
\end{array} \right] = \left[ \begin{array}{c}
u_2 \\
\frac{u_2^2}{u_1} + (\gamma -1) \left(u_3 - \frac{1}{2}\frac{u_2^2}{u_1} \right) \\
(u_3 + (\gamma -1) \left(u_3 - \frac{1}{2}\frac{u_2^2}{u_1} \right)) \frac{u_2}{u_1} \\
\end{array} \right] $$

\begin{equation}
  F_{i+1/2}= \frac{1}{2} \left( F \left( e_{i} \right) + F \left( e_{i+1} \right) -  \frac{\Delta x}{\Delta t} \left( e_{i+1} - e_{i} \right) \right)
\end{equation}



Test Conditions

In a tube spanning $x = -10m$ to $x = 10m$ with the rigid membrane at $x = 0m$ we have following initial gas states:

$$IC_L = \left[ \begin{array}{c}
\rho_L \\
u_L \\
p_L \\
\end{array} \right] = \left[ \begin{array}{c}
1kg/m^3 \\
0m/s \\
100 kN/m^2 \\
\end{array} \right] $$

$$IC_R = \left[ \begin{array}{c}
\rho_R \\
u_R \\
p_R \\
\end{array} \right] = \left[ \begin{array}{c}
.0125kg/m^3 \\
0m/s \\
10 kN/m^2 \\
\end{array} \right] $$

Where $IC_L$ are the inital density, velocity, and pressure onthe left side of the tube membrane and $IC_R$ are the density, velocity, pressure on the right side.

The Richtmyer method


$$\vec{u}_{i+\frac{1}{2}}^{n+\frac{1}{2}} = \frac{1}{2}(\vec{u}_{i+1}^n + \vec{u}_i^n) - \frac{\Delta t}{2 \Delta x}(\vec{f}_{i+1}^n - \vec{f}_i^n)$$

$$\vec{u}_{i}^{n+1} = \vec{u}_i^n - \frac{\Delta t}{\Delta x} \left( \vec{f}_{i+\frac{1}{2}}^{n+\frac{1}{2}} - \vec{f}_{i-\frac{1}{2}}^{n+\frac{1}{2}} \right)$$

The flux vectors used in the second step are obtained by evaluating the flux functions on the output of the first step:

$$\vec{f}_{i+\frac{1}{2}}^{n+\frac{1}{2}} = \vec{f} \left( \vec{u}_{i+\frac{1}{2}}^{n+\frac{1}{2}} \right)$$


Calculate the pressure, density, and velocity across the shock tube at time $t=0.01s$ using the Richtmyer method.

In [22]:
%matplotlib inline
import numpy
from numpy import *


In [291]:
def u_initial(nx):
    gamma = 1.4
    u = numpy.zeros((3,nx))
    u[0,:(nx-1)*2/4]=ICL[0]
    u[0,((nx-1)*2/4):]=ICR[0]
    
    u[1,:(nx-1)*2/4]=ICL[0]*ICL[1]
    u[1,((nx-1)*2/4):]=ICR[0]*ICR[1]
    
    u[2,:(nx-1)*2/4]=ICL[0]*(ICL[2]/((gamma-1)*ICL[0]))
    u[2,((nx-1)*2/4):]=ICR[0]*(ICR[2]/((gamma-1)*ICR[0]))
    
    return u


ICL = numpy.array([1.,
                  0.,
                  100000.])

ICR = numpy.array([0.125,
                  0.,
                  10000.])
nx=81
gamma = 1.4
dt = .0002
dx = 20.0/(nx-1)
nt = 51

def computeF(u):
    gamma = 1.4
    u_1 = u[0,:]
    u_2 = u[1,:]
    u_3 = u[2,:]
    return numpy.array([u_2,
                       (u_2**2/u_1)+(gamma-1)*(u_3-(1/2)*(u_2**2/u_1)),
                       (u_3 + (gamma-1)*(u_3-(1/2)*(u_2**2/u_1)))*(u_2/u_1)])


def richtmeyer(u, nt,dt,dx,nx):
    un = numpy.zeros((nt,3,nx))
    un[:,:,:] = u.copy()
    ustar = numpy.zeros_like(u)
    #un = u.copy()
    ustar = u.copy()
    
    for t in range(1,nt):
        f = computeF(u)
        
        ustar[:,:-1] = 0.5*(u[:,1:] + u[:,:-1]) - (dt/2*dx)*(f[:,1:] - f[:,:-1])
    
        fstar = computeF(ustar)
    
        un[t,:,1:-1] = u[:,1:-1] - dt/dx*(fstar[:,1:-1] - fstar[:,:-2])
    
        u = un[t,:,:].copy()
    
    return un

rho = richtmeyer(u_initial(nx), nt,dt,dx,nx)

print(rho[50:,:])
#print(u_initial(nx))
    
#print(computeF(u_initial(nx)))



[[[  1.00000000e+000   1.00000000e+000   1.00000000e+000   1.00000000e+000
     1.00000000e+000   1.00000000e+000   1.00000000e+000   1.00000000e+000
     1.00000000e+000   1.00000000e+000   1.00000000e+000   1.00000000e+000
     1.00000000e+000   9.99999999e-001   9.99999985e-001   9.99999957e-001
     9.99999434e-001   9.99998732e-001   9.99985370e-001   9.99974499e-001
     9.99741825e-001   9.99659290e-001   9.97001348e-001   2.32449270e+115
    -1.38767315e+119   3.50100559e+121   9.50296550e+140   8.88019352e+149
    -5.20596673e+150   1.73251147e+151  -7.27407146e+151  -4.32933353e+153
     3.26417379e+154               nan               nan               nan
                 nan               nan               nan               nan
                 nan               nan               nan               nan
                 nan               nan               nan               nan
                 nan               nan               nan               nan
                 nan     

//anaconda/lib/python3.4/site-packages/ipykernel/__main__.py:4: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
//anaconda/lib/python3.4/site-packages/ipykernel/__main__.py:5: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
//anaconda/lib/python3.4/site-packages/ipykernel/__main__.py:7: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
//anaconda/lib/python3.4/site-packages/ipykernel/__main__.py:8: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
//anaconda/lib/python3.4/site-packages/ipykernel/__main__.py:10: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
//anaconda/lib/python3.4/site-packages/ipykernel/__main__.py:11: DeprecationWarning: using a non-integer number instead of an integer will resul

In [84]:
print(20/80)

0.25


In [130]:
x = numpy.zeros((3,3,5))
print(x)

[[[ 0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.]]

 [[ 0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.]]

 [[ 0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.]]]


In [ ]:
x.....
.....x